apiVersion: batch/v1
kind: CronJob
metadata:
  name: db-backup
  namespace: {{ .Values.namespace }}
spec:
  schedule: {{ .Values.backup.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: alpine
            command: ["/bin/sh", "-c", "echo 'Taking DB backup...'"]
          restartPolicy: OnFailure

